# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '201wd.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import diy

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2000, 1400)


        self.MainWindow = MainWindow
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(100, 100, 560, 1020))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 60, 500, 820))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_2 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_2.addWidget(self.spinBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinBox_3 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_3.addWidget(self.spinBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        '''
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.spinBox_4 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout_4.addWidget(self.spinBox_4)'''
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(180, 940, 150, 45))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(1340, 120, 520, 1000))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(40, 60, 422, 822))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.spinBox_5 = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalLayout_5.addWidget(self.spinBox_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.spinBox_6 = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBox_6.setObjectName("spinBox_6")
        self.horizontalLayout_6.addWidget(self.spinBox_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.spinBox_7 = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBox_7.setObjectName("spinBox_7")
        self.horizontalLayout_7.addWidget(self.spinBox_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 920, 150, 45))
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(720, 100, 561, 1021))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 60, 500, 820))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.spinBox_8 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.spinBox_8.setObjectName("spinBox_8")
        self.horizontalLayout_8.addWidget(self.spinBox_8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.spinBox_9 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.spinBox_9.setObjectName("spinBox_9")
        self.horizontalLayout_9.addWidget(self.spinBox_9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.spinBox_10 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.spinBox_10.setObjectName("spinBox_10")
        self.horizontalLayout_10.addWidget(self.spinBox_10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.spinBox_11 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.spinBox_11.setObjectName("spinBox_11")
        self.horizontalLayout_11.addWidget(self.spinBox_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 940, 150, 45))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(880, 1300, 150, 45))
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1721, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.accepted1)
        self.pushButton_2.clicked.connect(self.accepted2)
        self.pushButton_3.clicked.connect(self.accepted3)
        self.pushButton_4.clicked.connect(self.accepted4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Layer 1st & initialize"))
        self.label.setText(_translate("MainWindow", "input i :"))
        self.label_2.setText(_translate("MainWindow", "input j :"))
        self.label_3.setText(_translate("MainWindow", "input number :"))
        #self.label_4.setText(_translate("MainWindow", "input total channels :"))
        self.pushButton.setText(_translate("MainWindow", "Apply"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Layer 3 creation"))
        self.label_5.setText(_translate("MainWindow", "input id of 2nd layer"))
        self.label_6.setText(_translate("MainWindow", "input i :"))
        self.label_7.setText(_translate("MainWindow", "input j :"))
        self.pushButton_3.setText(_translate("MainWindow", "Apply"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Layer 2nd creation"))
        self.label_8.setText(_translate("MainWindow", "input x coordinate :"))
        self.label_9.setText(_translate("MainWindow", "input y coordinate :"))
        self.label_10.setText(_translate("MainWindow", "input i :"))
        self.label_11.setText(_translate("MainWindow", "input j :"))
        self.pushButton_2.setText(_translate("MainWindow", "Apply"))
        self.pushButton_4.setText(_translate("MainWindow", "Quit"))

    def accepted1(self):
        try:
            # 获取 spinbox 的值
            a = self.spinBox.value()
            b = self.spinBox_2.value()
            num1 = self.spinBox_3.value()
            global layer1
            stat_layer1 = diy.generate_random_base_stations(num1, window_width, window_height,a,b,1)
            if stat_layer1 is not None:
                layer1 = layer1 + stat_layer1
                print("基站已重新排序1。")

        except Exception as e:
            print(f"发生错误: {e}")

    def accepted2(self):
        try:
            m = self.spinBox_10.value()
            n = self.spinBox_11.value()
            x = self.spinBox_8.value()
            y = self.spinBox_9.value()
            stat_layer2 = diy.generate_er(layer1, m, n, x, y, 2)
            global layer2
            if stat_layer2 is not None:
                layer2 = layer2 + stat_layer2
                print("基站已重新排序1。")

        except Exception as e:
            print(f"发生错误: {e}")

    def accepted3(self):
        try:
            m = self.spinBox_6.value()
            n = self.spinBox_7.value()
            Nu = self.spinBox_5.value()
            global layer2
            global layer3
            st_3 = diy.generate_san(layer2, m, n,Nu,3)
            if st_3 is not None:
                layer3 = layer3 + st_3
            print('ready')

        except Exception as e:
            print(f"发生错误: {e}")

    def accepted4(self):
        diy.save(filename,layer1+layer2+layer3)
        print('ready',len(layer1+layer2+layer3))
        self.MainWindow.close()


#vital info needed
clusters = []
# Constants for Pygame configuration (adjust these values accordingly)
window_width = 1000
window_height = 800
filename = 'data.txt'
network_types = [1,2,3,4]
layer1,layer2,layer3 = diy.read_base_stations_sp(filename, 9)

def main():
    app = QtWidgets.QApplication(sys.argv)

    # 创建一个 QDialog 实例
    QMW = QtWidgets.QMainWindow()

    # 创建 Ui_Dialog 实例
    ui = Ui_MainWindow()

    # 设置 QDialog 的 UI
    ui.setupUi(QMW)

    # 显示 QDialog 实例
    QMW.show()

    sys.exit(app.exec_())


if __name__ == '__main__':
    main()

    # 关闭对话框
    QtCore.QCoreApplication.instance().quit()